graph TD
    subgraph Identity Manager Platform
        linid-im-api-corelib[linid-im-api-corelib<br/>Plugin Runtime Engine]

        subgraph Plugins
            auth_plugins[Authorization Plugins<br/>RBack, Jwt, LDAP]
            provider_plugins[Provider Plugins<br/>LDAP, REST, DB]
            route_plugins[Route Plugins<br/>Custom Processing Flows]
            task_plugins[Task Plugins<br/>Phased Executions]
            validation_plugins[Validation Plugins<br/>Business Rules]
        end

        subgraph File system
            loader[Plugin binaries]
            config[Dynamic Config<br/>JSON/YAML]
        end

        subgraph External Systems
            identity[Identity Systems<br/>LDAP, SSO]
            databases[Databases]
            apis[External APIs]
        end

        subgraph API Rest
            crud[Default CRUD http routes]
            custom_routes[Custom http routes]
        end
    end

%% Flows
    config --> linid-im-api-corelib
    loader --> linid-im-api-corelib
    linid-im-api-corelib --> auth_plugins
    linid-im-api-corelib --> provider_plugins
    linid-im-api-corelib --> route_plugins
    linid-im-api-corelib --> task_plugins
    linid-im-api-corelib --> validation_plugins
    provider_plugins --> identity
    provider_plugins --> databases
    provider_plugins --> apis
    auth_plugins --> identity
    route_plugins --> crud
    route_plugins --> custom_routes
